version: '3'
services:

  redis:
    image: redis


  postgres:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: habit
      POSTGRES_PASSWORD: 225388
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"


  celery:
    build:
      context: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - api

  celery-beat:
    build:
      context: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - api