# Generated by Django 4.2.7 on 2023-11-08 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('action', models.CharField(blank=True, null=True, verbose_name='действие')),
                ('is_nice', models.BooleanField(blank=True, null=True, verbose_name='это приятно')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=250, null=True, verbose_name='награда')),
                ('time_to_complete', models.PositiveIntegerField(blank=True, default=45, null=True, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='опубликовано')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='связанная')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('name',),
            },
        ),
    ]
